### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by tangxs0808** [MirageNetwork/MirageServer#37]
在超管配置小程序端后无法登陆，小程序后端正常获取用户信息，用户登录界面扫码登录后还停留登录界面，后端提示无法获取token

**Comment by tangxs0808** [comment]
{"level":"info","time":"2023-11-24 21:48:54","message":"login successful: connector \"Microsoft\", username=\"先生 tom\", preferred_username=\"\", email=\"333332238@qq.com\", groups=[]"}
{"level":"warn","time":"2023-11-24 21:48:56","message":"未能从Cookie读取到OIDC Token！"}

**Comment by tangxs0808** [comment]
2023/11/24 21:58:31 http: panic serving 172.17.0.1:57668: runtime error: index out of range [0] with length 0
goroutine 325 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1f282c0?, 0xc00014a180?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
MirageNetwork/MirageServer/controller.(*Mirage).selectOrgForLogin(0x25f1710?, {0x25eb780, 0xc0000d1260}, 0xc000565d00)
	/app/MirageServer/controller/console_auth.go:626 +0xec
net/http.HandlerFunc.ServeHTTP(0xc000565c00?, {0x25eb780?, 0xc0000d1260?}, 0x1?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000d80, {0x25eb780, 0xc0000d1260}, 0xc000565b00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
net/http.serverHandler.ServeHTTP({0x25e7060?}, {0x25eb780?, 0xc0000d1260?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0007a0ea0, {0x25f1710, 0xc00074c720})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 33
	/usr/local/go/src/net/http/server.go:3086 +0x5cb
2023/11/24 21:58:33 http: panic serving 172.17.0.1:57686: runtime error: index out of range [0] with length 0
goroutine 327 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1f282c0?, 0xc00014a210?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
MirageNetwork/MirageServer/controller.(*Mirage).selectOrgForLogin(0x25f1710?, {0x25eb780, 0xc0000d1340}, 0xc0006a2000)
	/app/MirageServer/controller/console_auth.go:626 +0xec
net/http.HandlerFunc.ServeHTTP(0xc000565f00?, {0x25eb780?, 0xc0000d1340?}, 0x1?)
	/usr/local/go/src/net/http/server.go:2136 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000d80, {0x25eb780, 0xc0000d1340}, 0xc000565e00)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
net/http.serverHandler.ServeHTTP({0x25e7060?}, {0x25eb780?, 0xc0000d1340?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc0007a1050, {0x25f1710, 0xc00074c720})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 33
	/usr/local/go/src/net/http/server.go:3086 +0x5cb
